# Project Proposal

### Vrije Universiteit Amsterdam
### Minor in Data Science: Introduction to Data Science
#### Group 23 Members
* Bonolo Phoi
* Arianna Kuyasha Quispe Digiusto
* Gabrielle Barthelmy

## Introduction and Business Problem

Human Immunodeficiency Virus (HIV) affects millions of people worldwide, and Hepatitis B Virus (HBV) is one of the most common co-infections among people living with HIV due to their shared modes of transmission. People living with HIV are also more likely to develop chronic hepatitis, and HIV/HBV co-infection is particularly prevalent in sub-Saharan Africa (Chiesa et al., 2020; Dagnaw et al., 2025). This co-infection can complicate HIV treatment by increasing the risk of liver damage and other complications. Therefore, this project uses demographic, clinical, and viral exposure information from HIV-positive patients in Northern Uganda to identify factors associated with HBV co-infection. Specifically, we will use HBsAg status as the outcome variable in a multivariable regression model to determine which patient characteristics are associated with HBV positivity. Identifying these factors could help support earlier HBV screening and inform treatment decisions for people living with HIV, potentially reducing complications associated with undiagnosed co-infection.

In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

## Understanding the Data

This dataset contains information from 950 people living with HIV in Northern Uganda and was obtained from an academic study examining HIV and HBV coinfection. The dataset contains 26 variables covering patient demographics, HBV exposure history, HIV treatment, disease progression, and clinical laboratory measurements. The data will be used to examine the relationship between these patient characteristics and HBV infection. HBsAg status will serve as the outcome variable in our model, while relevant demographic, clinical, and exposure characteristics will be considered as predictors. The dataset provides patient-level information that allows us to examine multiple factors simultaneously rather than looking at HBV infection based on a single characteristic.

In [6]:
df = pd.read_csv('data/hivdata.csv')  
print("Number of observations:", df.shape[0])
print("Number of variables:", df.shape[1])


df.info()

Number of observations: 950
Number of variables: 26
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PATIENT'S ID               950 non-null    int64
 1   AGE                        949 non-null    float64
 2   GENDER                     950 non-null    object
 3   SEX WORKER                 950 non-null    object
 4   BLOOD TRANSFUSION          950 non-null    object
 5   HBsAg                      950 non-null    object
 6   REFUGEE CAMP               950 non-null    object
 7   USE OF INJECTION DRUGS     950 non-null    object
 8   MOTHER WITH HBV            950 non-null    object
 9   TRIBE                      950 non-null    object
 10  EDUCATION                  950 non-null    object
 11  HBV IN THE COMPOUND        950 non-null    object
 12  CIRCUMCISION               950 non-null    object
 13  THERAPY (YES/NO)           950 non-null    object
 14  MARITAL STATUS             950 non-null    object
 15  THERAPEUTIC SCARIFICATION  950 non-null    object
 16  Months in therapy          947 non-null    float64
 17  WHO stage at ART start     950 non-null    object
 18  WHO stage actual           950 non-null    object
 19  ALT                        889 non-null    float64
 20  AST                        887 non-null    float64
 21  CD4-DIAGNOSIS              781 non-null    float64
 22  CD4-START THERAPY          906 non-null    float64
 23  MORE RECENT CD4            903 non-null    float64
 24  START THERAPY              950 non-null    object
 25  ACTUAL THERAPY             950 non-null    object
dtypes: float64(7), int64(1), object(18)
memory usage: 193.1+ KB

## First 15 Entries of the Data

In [7]:

df.head(15)

,PATIENT'S ID,AGE,GENDER,SEX WORKER,BLOOD TRANSFUSION,HBsAg,REFUGEE CAMP,USE OF INJECTION DRUGS,MOTHER WITH HBV,TRIBE,...,Months in therapy,WHO stage at ART start,WHO stage actual,ALT,AST,CD4-DIAGNOSIS,CD4-START THERAPY,MORE RECENT CD4,START THERAPY,ACTUAL THERAPY
0,1,65.9,F,no,no,no,yes,no,don't know / no data,Acholi,...,135.0,3,2,NaN,NaN,70.0,70.0,507.0,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
1,2,30.4,F,no,no,no,yes,no,no,Acholi,...,65.0,no data,1,NaN,NaN,343.0,343.0,796.0,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
2,3,42.0,m,no,yes,no,no,no,no,Acholi,...,78.0,4,no data,NaN,NaN,4.0,4.0,198.0,3TC-AZT-(NVP/EFV/LPVr/ATVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
3,4,58.3,F,no,no,no,yes,no,no,Acholi,...,102.0,3,3,NaN,NaN,113.0,148.0,386.0,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
4,5,42.4,m,no,no,no,yes,no,no,Acholi,...,28.0,3,2,NaN,NaN,377.0,377.0,578.0,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),3
5,6,45.3,F,no,no,no,no,no,no,Acholi,...,115.0,2,2,NaN,NaN,78.0,78.0,344.0,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
6,7,47.3,F,no,no,no,no,no,no,Acholi,...,94.0,3,2,NaN,NaN,14.0,14.0,1073.0,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
7,8,46.3,F,no,no,no,yes,no,no,Acholi,...,80.0,no data,1,NaN,NaN,265.0,265.0,571.0,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
8,9,43.6,F,no,no,no,no,no,no,Acholi,...,8.0,no data,no data,NaN,NaN,645.0,421.0,761.0,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),no data
9,10,42.7,F,no,no,no,no,no,no,Acholi,...,80.0,4,no data,NaN,NaN,55.0,55.0,496.0,3TC-AZT-(NVP/EFV/LPVr/ATVr),3TC-AZT-(NVP/EFV/LPVr/ATVr)
10,11,68.6,F,no,no,no,yes,no,no,Acholi,...,139.0,2,no data,NaN,NaN,1080.0,1080.0,969.0,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
11,12,45.3,F,no,no,no,yes,no,don't know / no data,Acholi,...,130.0,3,no data,NaN,NaN,53.0,53.0,973.0,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
12,13,48.8,F,no,no,yes,yes,no,no,Acholi,...,50.0,no data,no data,NaN,NaN,656.0,339.0,716.0,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
13,14,34.7,m,no,no,no,yes,no,no,Acholi,...,26.0,no data,no data,NaN,NaN,325.0,325.0,642.0,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),no data
14,15,46.8,F,no,no,yes,no,no,don't know / no data,Acholi,...,74.0,2,2,NaN,NaN,58.0,58.0,458.0,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),2

## Data Limitations

The dataset contains missing values, including 169 missing observations for CD4-Diagnosis, 61 for ALT, and 63 for AST. Categorical variables have not yet been encoded into dummy variables and will require further preprocessing. The dataset focuses on patients from Northern Uganda, which may limit how well the results generalize to other populations. Some demographic and behavioral information is self-reported, which may introduce reporting error.

In [8]:
miss_values = df.isnull().sum()

miss_values[miss_values > 0]

AGE                    1
Months in therapy      3
ALT                   61
AST                   63
CD4-DIAGNOSIS        169
CD4-START THERAPY     44
MORE RECENT CD4       47
dtype: int64

## Original Article and Dataset 
- https://pmc.ncbi.nlm.nih.gov/articles/instance/7673526/bin/pone.0242278.s001.xlsx 
- [Hepatitis B and HIV coinfection in Northern Uganda: Is a decline in HBV prevalence on the horizon?](https://pmc.ncbi.nlm.nih.gov/articles/PMC7673526/)

Binary Data Preparation 
This section, prepares the binary outcome and predictor variables for binary classification. Thus encoding the HBsAg outcome variable as well as the predictor variables into a binary variables (0= negative/no, 1= positive/yes). It is to be observed that only 75 of 950 patients (7.9%) tested positive for HBsAg.

### Encoding HBsAg outcome varaiable

In [10]:
df ['HBsAg'].value_counts()

HBsAg
no     875
yes     75
Name: count, dtype: int64

In [11]:
df['HBsAg'].unique()

array(['no', 'yes'], dtype=object)

In [12]:
df ['HBsAg_binary'] = df ['HBsAg'].map({'no':0, 'yes':1})
df['HBsAg_binary'].value_counts()

HBsAg_binary
0    875
1     75
Name: count, dtype: int64

### Identifying Categorical Predictors

In [15]:
df.select_dtypes(include='object')

,GENDER,SEX WORKER,BLOOD TRANSFUSION,HBsAg,REFUGEE CAMP,USE OF INJECTION DRUGS,MOTHER WITH HBV,TRIBE,EDUCATION,HBV IN THE COMPOUND,CIRCUMCISION,THERAPY (YES/NO),MARITAL STATUS,THERAPEUTIC SCARIFICATION,WHO stage at ART start,WHO stage actual,START THERAPY,ACTUAL THERAPY
0,F,no,no,no,yes,no,don't know / no data,Acholi,no formal education,1-no,no,yes,widow/widowed,no,3,2,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
1,F,no,no,no,yes,no,no,Acholi,completed primary school,2-yes,no,yes,married/cohabiting,no,no data,1,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
2,m,no,yes,no,no,no,no,Acholi,qualification afther senior six,1-no,yes,yes,married/cohabiting,yes,4,no data,3TC-AZT-(NVP/EFV/LPVr/ATVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
3,F,no,no,no,yes,no,no,Acholi,no formal education,1-no,no,yes,widow/widowed,yes,3,3,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
4,m,no,no,no,yes,no,no,Acholi,no formal education,1-no,no,yes,married/cohabiting,yes,3,2,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,F,no,no,no,no,no,don't know / no data,Acholi,no formal education,3-don't know / no data,no,yes,widow/widowed,yes,2,1,3TC-AZT-(NVP/EFV/LPVr/ATVr),2
946,F,no,no,no,yes,no,no,Acholi,completed primary school,1-no,no,yes,single,no,1,1,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),1
947,F,no,no,no,yes,no,don't know / no data,Acholi,no formal education,3-don't know / no data,no,yes,married/cohabiting,no,2,1,3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr),2
948,F,no,no,no,yes,no,don't know / no data,Acholi,no formal education,3-don't know / no data,no,yes,widow/widowed,no,3,2,FTC-TDF-(NVP/EFV/LPVr),3TC-TDF-(NVP/EFV/AZT/LPVr/ATVr)
949,F,no,yes,no,no,no,don't know / no data,Acholi,no formal education,3-don't know / no data,no,yes,single,no,2,2,3TC-AZT-(NVP/EFV/LPVr/ATVr),2

In [17]:
df.select_dtypes(include='object').columns

Index(['GENDER', 'SEX WORKER', 'BLOOD TRANSFUSION', 'HBsAg', 'REFUGEE CAMP',
       'USE OF INJECTION DRUGS', 'MOTHER WITH HBV', 'TRIBE', 'EDUCATION',
       'HBV IN THE COMPOUND', 'CIRCUMCISION', 'THERAPY (YES/NO)',
       'MARITAL STATUS', 'THERAPEUTIC SCARIFICATION', 'WHO stage at ART start',
       'WHO stage actual', 'START THERAPY', 'ACTUAL THERAPY'],
      dtype='object')

### GENDER variable

In [19]:
df['GENDER'].value_counts()

GENDER
F     736
m     214
Name: count, dtype: int64

In [20]:
df['GENDER'].unique()

array(['F ', 'm'], dtype=object)

In [21]:
df['GENDER_binary'] = df ['GENDER'].map({'m':0, 'F ':1})
df['GENDER_binary'].value_counts()

GENDER_binary
1    736
0    214
Name: count, dtype: int64

### SEX WORKER variable

In [22]:
df['SEX WORKER'].value_counts()

SEX WORKER
no      946
yes       4
Name: count, dtype: int64

In [23]:
df['SEX WORKER'].unique()

array(['no', 'yes '], dtype=object)

In [24]:
df['SEX WORKER_binary'] = df ['SEX WORKER'].map({'no':0, 'yes ':1})
df['SEX WORKER_binary'].value_counts()

SEX WORKER_binary
0    946
1      4
Name: count, dtype: int64

### BLOOD TRANSFUSION variable

In [25]:
df['BLOOD TRANSFUSION'].value_counts()

BLOOD TRANSFUSION
no     837
yes    113
Name: count, dtype: int64

In [26]:
df['BLOOD TRANSFUSION'].unique()

array(['no', 'yes'], dtype=object)

In [27]:
df['BLOOD TRANSFUSION_binary'] = df['BLOOD TRANSFUSION'].map({'no':0,'yes':1})
df['BLOOD TRANSFUSION_binary'].value_counts()

BLOOD TRANSFUSION_binary
0    837
1    113
Name: count, dtype: int64

### REFUGEE CAMP variable

In [28]:
df['REFUGEE CAMP'].value_counts()

REFUGEE CAMP
no      476
yes     474
Name: count, dtype: int64

In [29]:
df['REFUGEE CAMP'].unique()

array(['yes ', 'no'], dtype=object)

In [30]:
df['REFUGEE CAMP_binary'] = df['REFUGEE CAMP'].map({'no':0,'yes ':1})
df['REFUGEE CAMP_binary'].value_counts()

REFUGEE CAMP_binary
0    476
1    474
Name: count, dtype: int64

### USE OF INJECTION DRUGS variables

In [31]:
df ['USE OF INJECTION DRUGS'].value_counts()

USE OF INJECTION DRUGS
no     917
yes     33
Name: count, dtype: int64

In [32]:
df['USE OF INJECTION DRUGS'].unique()

array(['no', 'yes'], dtype=object)

In [33]:
df['USE OF INJECTION DRUGS_binary'] = df['USE OF INJECTION DRUGS'].map({'no':0,'yes':1})
df['USE OF INJECTION DRUGS_binary'].value_counts()

USE OF INJECTION DRUGS_binary
0    917
1     33
Name: count, dtype: int64

### MOTHER WITH HBV variable

In [35]:
df ['MOTHER WITH HBV'].value_counts()

MOTHER WITH HBV
no                      635
don't know / no data    308
Yes                       7
Name: count, dtype: int64

In [36]:
df ['MOTHER WITH HBV'].unique()

array(["don't know / no data", 'no ', 'Yes'], dtype=object)

'don't know/ no data' observations have been treated like missing values (NaN) since they dont represent clear yes or no answers

In [37]:
df['MOTHER WITH HBV_binary'] = df['MOTHER WITH HBV'].map({'no ':0,'Yes':1})
df['MOTHER WITH HBV_binary'].value_counts()

MOTHER WITH HBV_binary
0.0    635
1.0      7
Name: count, dtype: int64

### HBV IN THE COMPOUNT variable

In [38]:
df ['HBV IN THE COMPOUND'].value_counts()

HBV IN THE COMPOUND
1-no                      698
3-don't know / no data    197
2-yes                      55
Name: count, dtype: int64

In [39]:
df ['HBV IN THE COMPOUND'].unique()

array(['1-no ', '2-yes ', "3-don't know / no data"], dtype=object)

In [40]:
df ['HBV IN THE COMPOUND_binary'] = df ['HBV IN THE COMPOUND'].map({'1-no ':0,'2-yes ':1})
df['HBV IN THE COMPOUND_binary'].value_counts()

HBV IN THE COMPOUND_binary
0.0    698
1.0     55
Name: count, dtype: int64

### THERAPY variable

In [41]:
df ['THERAPY (YES/NO)'].value_counts()

THERAPY (YES/NO)
yes    950
Name: count, dtype: int64

In [42]:
df ['THERAPY (YES/NO)'].unique()

array(['yes'], dtype=object)

In [43]:
df['THERAPY (YES/NO)_binary'] = df['THERAPY (YES/NO)'].map({'no':0,'yes':1})
df['THERAPY (YES/NO)_binary'].value_counts()

THERAPY (YES/NO)_binary
1    950
Name: count, dtype: int64

### THERAPEUTIC SCARIFICATION

In [44]:
df ['THERAPEUTIC SCARIFICATION'].value_counts()

THERAPEUTIC SCARIFICATION
no     633
yes    317
Name: count, dtype: int64

In [45]:
df ['THERAPEUTIC SCARIFICATION'].unique()

array(['no', 'yes'], dtype=object)

In [46]:
df['THERAPEUTIC SCARIFICATION_binary'] = df['THERAPEUTIC SCARIFICATION'].map({'no':0,'yes':1})
df['THERAPEUTIC SCARIFICATION_binary'].value_counts()

THERAPEUTIC SCARIFICATION_binary
0    633
1    317
Name: count, dtype: int64

In [49]:

#print (df.columns.to_list())
categorical_columns= ['REFUGEE CAMP','TRIBE', 'EDUCATION']
encoder= OneHotEncoder(handle_unknown='ignore', sparse_output=False, dtype=int)
encoded= encoder.fit_transform(df[categorical_columns])
encoded_df= pd.DataFrame(encoded, columns= encoder.get_feature_names_out(categorical_columns))
#print(encoded_df.head())

df.head(10)
#df.columns.tolist()

,PATIENT'S ID,AGE,GENDER,SEX WORKER,BLOOD TRANSFUSION,HBsAg,REFUGEE CAMP,USE OF INJECTION DRUGS,MOTHER WITH HBV,TRIBE,...,HBsAg_binary,GENDER_binary,SEX WORKER_binary,BLOOD TRANSFUSION_binary,REFUGEE CAMP_binary,USE OF INJECTION DRUGS_binary,MOTHER WITH HBV_binary,HBV IN THE COMPOUND_binary,THERAPY (YES/NO)_binary,THERAPEUTIC SCARIFICATION_binary
0,1,65.9,F,no,no,no,yes,no,don't know / no data,Acholi,...,0,1,0,0,1,0,NaN,0.0,1,0
1,2,30.4,F,no,no,no,yes,no,no,Acholi,...,0,1,0,0,1,0,0.0,1.0,1,0
2,3,42.0,m,no,yes,no,no,no,no,Acholi,...,0,0,0,1,0,0,0.0,0.0,1,1
3,4,58.3,F,no,no,no,yes,no,no,Acholi,...,0,1,0,0,1,0,0.0,0.0,1,1
4,5,42.4,m,no,no,no,yes,no,no,Acholi,...,0,0,0,0,1,0,0.0,0.0,1,1
5,6,45.3,F,no,no,no,no,no,no,Acholi,...,0,1,0,0,0,0,0.0,0.0,1,0
6,7,47.3,F,no,no,no,no,no,no,Acholi,...,0,1,0,0,0,0,0.0,0.0,1,0
7,8,46.3,F,no,no,no,yes,no,no,Acholi,...,0,1,0,0,1,0,0.0,0.0,1,0
8,9,43.6,F,no,no,no,no,no,no,Acholi,...,0,1,0,0,0,0,0.0,0.0,1,0
9,10,42.7,F,no,no,no,no,no,no,Acholi,...,0,1,0,0,0,0,0.0,0.0,1,0